versions:
  - ver: 'master'
    repos:
        - name: onos-config
          url: https://github.com/onosproject/onos-config
          tagName: master
        - name: onos-topo
          url: https://github.com/onosproject/onos-topo
          tagName:  master
        - name: onos-gui
          url: https://github.com/onosproject/onos-gui
          tagName:  master
        - name: onos-test
          url: https://github.com/onosproject/onos-test
          tagName:  master
        - name: onos-cli
          url: https://github.com/onosproject/onos-cli
          tagName:  master
        - name: onos-ztp
          url: https://github.com/onosproject/onos-ztp
          tagName:  master
  - ver: '1.0'
    repos:
        - name: onos-config
          url: https://github.com/onosproject/onos-config
          tagName: v1.0-onfconnect
        - name: onos-topo
          url: https://github.com/onosproject/onos-topo
          tagName: v1.0-onfconnect
